import { Role } from '../users/schemas/role.schema';

export const generateRoles = (): Partial<Role>[] => {
  return [
    {
      name: 'Super Admin',
      description: 'Quản trị viên cao cấp với tất cả quyền hạn',
      isOrder: true,
      isProduct: true,
      isCategory: true,
      isPost: true,
      isVoucher: true,
      isBanner: true,
      isAnalytic: true,
      isReturn: true,
      isUser: true,
      isRole: true,
      isActive: true,
      priority: 100,
    },
    {
      name: 'Product Manager',
      description: 'Quản lý sản phẩm và danh mục',
      isOrder: false,
      isProduct: true,
      isCategory: true,
      isPost: false,
      isVoucher: false,
      isBanner: false,
      isAnalytic: true,
      isReturn: false,
      isUser: false,
      isRole: false,
      isActive: true,
      priority: 50,
    },
    {
      name: 'Order Manager',
      description: 'Quản lý đơn hàng và xử lý đơn hàng trả',
      isOrder: true,
      isProduct: false,
      isCategory: false,
      isPost: false,
      isVoucher: false,
      isBanner: false,
      isAnalytic: true,
      isReturn: true,
      isUser: false,
      isRole: false,
      isActive: true,
      priority: 40,
    },
    {
      name: 'Content Manager',
      description: 'Quản lý bài viết và banner',
      isOrder: false,
      isProduct: false,
      isCategory: false,
      isPost: true,
      isVoucher: false,
      isBanner: true,
      isAnalytic: true,
      isReturn: false,
      isUser: false,
      isRole: false,
      isActive: true,
      priority: 30,
    },
    {
      name: 'Marketing Manager',
      description: 'Quản lý voucher và marketing',
      isOrder: false,
      isProduct: false,
      isCategory: false,
      isPost: false,
      isVoucher: true,
      isBanner: true,
      isAnalytic: true,
      isReturn: false,
      isUser: false,
      isRole: false,
      isActive: true,
      priority: 35,
    },
    {
      name: 'User Manager',
      description: 'Quản lý người dùng và vai trò',
      isOrder: false,
      isProduct: false,
      isCategory: false,
      isPost: false,
      isVoucher: false,
      isBanner: false,
      isAnalytic: false,
      isReturn: false,
      isUser: true,
      isRole: true,
      isActive: true,
      priority: 60,
    },
    {
      name: 'Analytics Viewer',
      description: 'Chỉ xem thống kê và báo cáo',
      isOrder: false,
      isProduct: false,
      isCategory: false,
      isPost: false,
      isVoucher: false,
      isBanner: false,
      isAnalytic: true,
      isReturn: false,
      isUser: false,
      isRole: false,
      isActive: true,
      priority: 10,
    },
  ];
}; 